# 这是一个帮助您快速上手 Actions 的基础工作流

name: CI



  # 仅在“main”分支发生 push 或 pull request 事件时触发工作流
 推送:
    branches: [ "main" ]
 拉取请求:
    branches: [ "main" ]

  # 允许您从“Actions”选项卡手动运行此工作流
 workflow_dispatch:

# 一个工作流运行由一个或多个作业组成，这些作业可以按顺序执行，也可以并行执行
jobs:
  # 此工作流包含一个名为“build”的单个作业
  构建:
    # 该作业将运行的运行器类型
    运行操作系统: ubuntu-latest

    # 步骤表示作为作业一部分将要执行的一系列任务
    steps:
      # 将您的仓库检出到 $GITHUB_WORKSPACE 目录下，以便您的作业可以访问它
      - 使用: actions/checkout@v4

      # 使用 runner 的 shell 运行单条命令
      - name: 运行一段单行脚本
        run: echo Hello, world!

      # 使用 runner 的 shell 运行一组命令
      - 名称: 运行多行脚本
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
